export default {
  OWNER_NAME: 'Udbhav Mani',
  MENU_PRICE: 137,
  ORDER_SUCCESSFUL: 'Order Placed Successfully',
  PLACE_ORDER_HEADER: 'Place Order',
  PLACE_ORDER_BTN: 'Place Order',
  CURRENT_BALANCE_LABEL: 'Current Balance : ₹',
  BALANCE_LABEL: 'Balance',
  UPDATE_BALANCE_LABEL: 'Update Balance',
  ID_LABEL: 'Employee ID',
  TOTAL_BILL: 'Total Bill : ₹',
  NAME_LABEL: 'Name : ',
  SUCCESS_MESSAGE: 'Success',
  ERROR_MESSAGE: 'Error',
  AUTH_LOGGED_IN: 'Successfully logged in.',
  AUTH_LOGGED_IN_ERROR: 'Error logging in.',
  AUTH_INVALID_CREDENTIALS: 'Invalid username or password.',
  WELCOME: 'Welcome',
  USERNAME_LABEL: 'Username',
  PASSWORD_LABEL: 'Password',
  LOG_IN_BTN: 'Log In',
  LOG_OUT: 'Logged out',
  LOG_OUT_SUMMARY: 'Successfully logged out',
  EMP_LIST_HEADER: 'List of employees',
  RUPEE_SYMBOL: '₹',
  SEARCH_SYMBOL: '🔍',
  CRITERIA_LABEL: 'Criteria',
  RATINGS_LABEL: 'Ratings(Out of 5)',
  REVIEW_LABEL: 'Reviews',
  ADD_FDB_LABEL: 'Add feedback',
  SUBMIT_LABEL: 'Submit',
  ORDER_NOT_PLACED: 'Please place an order before giving feedback.',
  FDB_GIVEN_LABEL: 'You have already given feedback, Thank You!',
  STARS: ' * * * * * ',
  ERROR_OCCURED: 'An error occcured',
  FDB_SUBMITTED: 'Feedback submitted successfully!',
  FDB_SUBMITTED_DETAIL: 'Thank you for your feedback.',
  FDB_LABEL: 'Feedbacks',
  ALL_FDB_LABEL: 'All Feedbacks',
  NO_FDB_LABEL: 'No Feedbacks available',
  LOGOUT_LABEL: 'Logout',
  MENU_SUGGESTED_SUCCESS: 'New Menu suggested successfully.',
  MENU_DISCARDED_SUCCESS: 'Menu Discarded successfully.',
  ADD_BTN_LABEL: 'Add',
  ADD_CRITERIA_LABEL: 'Add Criteria',
};
